// Code generated by go generate; DO NOT EDIT.
// This file is automatically generated from checks in checks/

package pgdoctor

import (
	"github.com/fresha/pgdoctor/check"
	"github.com/fresha/pgdoctor/checks/cacheefficiency"
	"github.com/fresha/pgdoctor/checks/connectionefficiency"
	"github.com/fresha/pgdoctor/checks/connectionhealth"
	"github.com/fresha/pgdoctor/checks/devindexes"
	"github.com/fresha/pgdoctor/checks/duplicateindexes"
	"github.com/fresha/pgdoctor/checks/freezeage"
	"github.com/fresha/pgdoctor/checks/indexbloat"
	"github.com/fresha/pgdoctor/checks/indexusage"
	"github.com/fresha/pgdoctor/checks/invalidindexes"
	"github.com/fresha/pgdoctor/checks/partitioning"
	"github.com/fresha/pgdoctor/checks/partitionusage"
	"github.com/fresha/pgdoctor/checks/pgversion"
	"github.com/fresha/pgdoctor/checks/pktypes"
	"github.com/fresha/pgdoctor/checks/replicationlag"
	"github.com/fresha/pgdoctor/checks/replicationslots"
	"github.com/fresha/pgdoctor/checks/sequencehealth"
	"github.com/fresha/pgdoctor/checks/sessionsettings"
	"github.com/fresha/pgdoctor/checks/statisticsfreshness"
	"github.com/fresha/pgdoctor/checks/tableactivity"
	"github.com/fresha/pgdoctor/checks/tablebloat"
	"github.com/fresha/pgdoctor/checks/tableseqscans"
	"github.com/fresha/pgdoctor/checks/tablevacuumhealth"
	"github.com/fresha/pgdoctor/checks/tempusage"
	"github.com/fresha/pgdoctor/checks/toaststorage"
	"github.com/fresha/pgdoctor/checks/uuiddefaults"
	"github.com/fresha/pgdoctor/checks/uuidtypes"
	"github.com/fresha/pgdoctor/checks/vacuumsettings"
	"github.com/fresha/pgdoctor/db"
)

// AllChecks returns all available check packages.
// Consumers call .Metadata() for check information or .New(conn) to instantiate checkers.
func AllChecks() []check.CheckPackage {
	return []check.CheckPackage{
		{
			Metadata: cacheefficiency.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return cacheefficiency.New(db.New(conn))
			},
		},
		{
			Metadata: connectionefficiency.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return connectionefficiency.New(db.New(conn))
			},
		},
		{
			Metadata: connectionhealth.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return connectionhealth.New(db.New(conn))
			},
		},
		{
			Metadata: devindexes.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return devindexes.New(db.New(conn))
			},
		},
		{
			Metadata: duplicateindexes.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return duplicateindexes.New(db.New(conn))
			},
		},
		{
			Metadata: freezeage.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return freezeage.New(db.New(conn))
			},
		},
		{
			Metadata: indexbloat.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return indexbloat.New(db.New(conn))
			},
		},
		{
			Metadata: indexusage.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return indexusage.New(db.New(conn))
			},
		},
		{
			Metadata: invalidindexes.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return invalidindexes.New(db.New(conn))
			},
		},
		{
			Metadata: partitioning.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return partitioning.New(db.New(conn))
			},
		},
		{
			Metadata: partitionusage.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return partitionusage.New(db.New(conn))
			},
		},
		{
			Metadata: pgversion.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return pgversion.New(db.New(conn))
			},
		},
		{
			Metadata: pktypes.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return pktypes.New(db.New(conn))
			},
		},
		{
			Metadata: replicationlag.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return replicationlag.New(db.New(conn))
			},
		},
		{
			Metadata: replicationslots.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return replicationslots.New(db.New(conn))
			},
		},
		{
			Metadata: sequencehealth.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return sequencehealth.New(db.New(conn))
			},
		},
		{
			Metadata: sessionsettings.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return sessionsettings.New(db.New(conn))
			},
		},
		{
			Metadata: statisticsfreshness.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return statisticsfreshness.New(db.New(conn))
			},
		},
		{
			Metadata: tableactivity.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return tableactivity.New(db.New(conn))
			},
		},
		{
			Metadata: tablebloat.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return tablebloat.New(db.New(conn))
			},
		},
		{
			Metadata: tableseqscans.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return tableseqscans.New(db.New(conn))
			},
		},
		{
			Metadata: tablevacuumhealth.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return tablevacuumhealth.New(db.New(conn))
			},
		},
		{
			Metadata: tempusage.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return tempusage.New(db.New(conn))
			},
		},
		{
			Metadata: toaststorage.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return toaststorage.New(db.New(conn))
			},
		},
		{
			Metadata: uuiddefaults.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return uuiddefaults.New(db.New(conn))
			},
		},
		{
			Metadata: uuidtypes.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return uuidtypes.New(db.New(conn))
			},
		},
		{
			Metadata: vacuumsettings.Metadata,
			New: func(conn db.DBTX) check.Checker {
				return vacuumsettings.New(db.New(conn))
			},
		},
	}
}
